site_name: ERP Sankhya - Manual Técnico
theme:
  name: material

repo_url: https://github.com/DadyIlha/sankhya-doc/
repo_name: GitHub

nav:
  - Introdução: "index.md"
  - "Instalação e Configuração":
      - "Passo 1: Instalação": "guia/passo1.md"
      - "Passo 2: Configuração": "guia/passo2.md"
